# docker-compose.dev.yml
version: '3.8'

services:
  app:
    platform: linux/arm64
    container_name: myapp-front
    image: myapp-front-dev:myapp-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: development
    ports:
      - "3000:3000"
    environment:
      MODE: development
    volumes:
      - ./src:/app/src:cached