# docker-compose.prod.yml
services:
  app:
    platform: linux/arm64
    container_name: mins-frame-prod
    image: mins-frame-prod:mins-frame-prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: production
    ports:
      - "3000:3000"
    environment:
      - MODE=production
    env_file:
      - .env