# docker-compose.prod.yml
name: ${PROJECT_NAME}-${MODE}
services:
  app:
    platform: linux/arm64
    container_name: ${PROJECT_NAME}-${SERVICE_NAME}
    image: ${PROJECT_NAME}:${SERVICE_NAME}
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODE: production
    ports:
      - "${PORT_NUMBER}:3000"
    environment:
      - MODE=production
    env_file:
      - ../.env