# docker-compose.dev.yml
name: ${PROJECT_NAME}-${MODE}
services:
  app:
    platform: linux/arm64
    container_name: ${SERVICE_NAME}
    image: ${PROJECT_NAME}:${SERVICE_NAME}
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODE: development
    ports:
      - "${PORT_NUMBER}:3000"
    environment:
      MODE: development
    volumes:
      - ../src:/app/src:cached