# docker-compose.yml
name: ${PROJECT_NAME}-${MODE}

services:
  frontend:
    platform: linux/arm64
    container_name: ${PROJECT_NAME}-frontend
    image: ${PROJECT_NAME}:frontend
    build:
      context: ..
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - ../.env

  backend:
    platform: linux/arm64
    container_name: ${PROJECT_NAME}-backend
    image: ${PROJECT_NAME}:backend
    build:
      context: ..
      dockerfile: backend/Dockerfile.backend
    ports:
      - "5001:5001"
    env_file:
      - ../.env
